### ISSUE TITLE
Drop safe-buffer dependency after 2018-04-30

### ISSUE THREAD

**Issue by silverwind** [mafintosh/dns-packet#20]
The dependency can safely be dropped in Node.js 6 or higher (the used methods were introduced in 5.12), just adding this here so we don't forget.

**Comment by silverwind** [comment]
Node v4 will EOL on 2018-04-30.

**Comment by pusateri** [comment]
The Node v4 EOL is official now.

**Comment by silverwind** [comment]
Yeah, will do before next release.
