### ISSUE TITLE
Unify header flag names (breaking)

### ISSUE THREAD

**Issue by silverwind** [mafintosh/dns-packet#27]
We currently have these header flag booleans:
````
flag_auth
flag_trunc
flag_rd
flag_ra
flag_z
flag_ad
flag_cd
````
I notices that there is a registered list of 2-character flag names [here](https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-12) and I think we should use `flag_{xx}` naming scheme. Note that this is a breaking change on `flag_auth`, `flag_trunc` and `flag_z` (which is reserved and should likely be removed, unless there's a use case for it).

cc: @pusateri

**Comment by pusateri** [comment]
This make sense. It's better to fix it now before there are more dependencies.

**Comment by silverwind** [comment]
I' get to it. I think I'll leave `flag_z` as-is because it goes by that name in the rfc.

**Comment by pusateri** [comment]
Good. It's nice to have some way to reference it even though it's unassigned.
