### ISSUE TITLE
Add DNS over HTTPS (doh) example

### ISSUE THREAD

**Issue by pusateri** [mafintosh/dns-packet#30]
[doh client example using dns-packet here](https://github.com/pusateri/doh-client)
I can add this to examples.

Based on this [internet-draft](https://tools.ietf.org/html/draft-ietf-doh-dns-over-https-03)

**Comment by silverwind** [comment]
Sounds good. This will be useful for anyone building a doh client or server.

**Comment by mafintosh** [comment]
love that this is called doh

**Comment by silverwind** [comment]
![](https://coloradopeakpolitics.com/wp-content/uploads/2015/08/doh.gif)
