### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by pusateri** [mafintosh/dns-packet#35]
Anyone interested in supporting typescript in this project?

**Comment by silverwind** [comment]
Can't say I'm interested, but I won't block if you want to maintain definitions.

**Comment by pusateri** [comment]
No worries.

**Comment by small-sunshines** [comment]
I have a Type definition file created by using this module in TypeScript this time. I do not know, however, that this definition is precisely defined. However, it is defined to the extent that I can use it.
