### ISSUE TITLE
Support EDNS0

### ISSUE THREAD

**Issue by hildjj** [mafintosh/dns-packet#36]
Feature Request:
Support encoding [RFC 2671](https://tools.ietf.org/html/rfc2671) OPT RRs.  I'm working up a PR.

**Comment by silverwind** [comment]
FYI: We have already one PR pending for EDNS: https://github.com/mafintosh/dns-packet/pull/34

That one adds OPT support, but currently does not handle the RDATA parts. I suggest you corrdinate with @pusateri.

**Comment by hildjj** [comment]
Will coordinate. Close this if you like.
