### ISSUE TITLE
Make coverage checking repeatable

### ISSUE THREAD

**Issue by hildjj** [mafintosh/dns-packet#48]
Proposal: 

- [ ] add [nyc](https://github.com/istanbuljs/nyc#readme) as a dev dependency
- [ ] Add a `coverage` script to `package.json` that generates HTML
- [ ] Add coverage outputs to `.gitignore`

Optional, if desired (trivial for me to do, but more controversial):
- [ ] Install [coveralls](https://github.com/nickmerwin/node-coveralls#readme) in `.travis.yml`
- [ ] On successful run, send output to [coveralls.io](https://coveralls.io/)
- [ ] Add support for auto-refresh of the coverage HTML (makes writing coverage tests fun)

**Comment by hildjj** [comment]
Coverage output [sample](https://coveralls.io/github/hildjj/dns-packet?branch=coverage).

**Comment by silverwind** [comment]
Sounds good, I'd actually appreciate a coverage badge in the `README`, so I think this means we need to upload the reports. Note that I have no experience with coverage tools really.

**Comment by hildjj** [comment]
You'll need a coveralls.io account (log in with github), and turn on support for this repo by clicking the "+" on the left side, searching for the repo name, and sliding the button to "on".  My PR will include a (correct) badge.
