### ISSUE TITLE
11 MB "node010" file 

### ISSUE THREAD

**Issue by borian** [mafintosh/dns-packet#8]
After installation via NPM, there is an 11MB file in the dns-packet folder.

I can't find a reference to it.
Is there a reason for it being there?

![test](https://i.imgur.com/x3k2J7ll.png)

**Comment by silverwind** [comment]
That file (which is a node 0.10 binary) got included accidentially while I was testing a node 0.10 issue. I added the `files` option in package.json to prevent such issues in the future, sorry.
