### ISSUE TITLE
docs: mention 🍊 `tangerine` if the user needs a complete 1:1 replacement for `dns.promises.Resolver`?

### ISSUE THREAD

**Issue by titanism** [mafintosh/dns-packet#86]
Hey 👋   Just writing to express thanks for making `dns-packet` &ndash; it made creating 🍊 [Tangerine](https://github.com/forwardemail/tangerine) `npm install tangerine` possible.  [We shared thanks](https://github.com/forwardemail/tangerine#what-projects-were-used-for-inspiration) in our README too!  Just passing this note along in case you also wanted to mention in `dns-packet`'s README this project.  It uses `dns-packet` under the hood!

**Comment by silverwind** [comment]
Not sure I'm interesting in calling out specific depdendees, sorry. If there is automated "who uses this" embed for the readme, we can add it I guess.
