### ISSUE TITLE
please add the NAPTR record support

### ISSUE THREAD

**Issue by xuhjbj** [mafintosh/dns-packet#87]
https://en.wikipedia.org/wiki/NAPTR_record

Currently,dns-packet does not support this query type.Please help add this.Thanks.

**Comment by xunavy** [comment]
any update for this issue ？

**Comment by silverwind** [comment]
Pull Request welcome.

**Comment by silverwind** [comment]
https://github.com/mafintosh/dns-packet/commit/aca1ff751cc9c38862d652bac26fe31d2fcce32b
