### ISSUE TITLE
what is node010?

### ISSUE THREAD

**Issue by Pomax** [mafintosh/dns-packet#9]
Installing this package drops an 11MB (!) file called "node010" in the module dir: what is this file? Is this, as the name might seem to suggest, a single-file compiled node 0.10? What is it used for? Can the README.md be extend to explain what this file is and what its security implications are (because this is a DNS package, there are *always* security implications)

**Comment by mafintosh** [comment]
Was prob published by accident. Either way, latest version (1.2.2) doesn't have this accidental file.

**Comment by mafintosh** [comment]
Ah, see #8

**Comment by silverwind** [comment]
Yes, my fault. I tend to leave unrelated files in package directories because I use `files` in all my projects to define exactly what gets published. Anyways, I've added `files` to both `dns-packet` and `dns-socket` now to prevent future issues.

**Comment by Pomax** [comment]
cool, I'll let the `create-react-app` folks know that they might want to have a quick look at their dependency chain (ran into this while bootstrapping a throw-away react app =)
